### ISSUE TITLE
Lead image and collective.nitf

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.behavior.amp#19]
For us, the main use of this package will be with [collective.nitf](https://github.com/collective/collective.nitf).

Currently, the [lead image implementation](https://github.com/collective/collective.behavior.amp/blob/f8c0f8e55dd0a862a94646ec434af0106b09eb12/src/collective/behavior/amp/browser/__init__.py#L167-L185) looks for `image` and `image_caption` attributes; those must be instances of `NamedBlobImage` and `str`.

That should work for standard News Items and any other content types providing the lead image interface, but in collective.nitf we have some problems:
- [version 1.x](https://github.com/collective/collective.nitf/blob/1.0b8/src/collective/nitf/content.py#L126-L139) (currently in production on most of our news sites) has `image` and `imageCaption` methods; both of them are callables that return an instance of the `Image` content type, and `str`
- [version 2.x](https://github.com/collective/collective.nitf/blob/2.0b3/src/collective/nitf/content.py#L32-L42) has `image` and `media_caption` methods that are an instance of the `Image` content type, and `str`

We have two different ways to solve this:
- workaround this API incompatibilities inside this package:
  - seems easier :grey_question: 
  - we must maintain it in this code base where it doesn't belong :x:  
- fix collective.nitf methods to return the right values and release new minor versions (1.1 and 2.1):
  - conceptually the right way to implement lead image :white_check_mark:
  - future proof :white_check_mark:
  - needs further testing as we may cause issues in current deployments :bomb:

**Comment by hvelarde** [comment]
@agnogueira @rodfersou @idgserpro comments, please.

**Comment by rodfersou** [comment]
I think the right place to fix it is at collective.nitf package, we should deprecate the `imageCaption` and `media_caption` methods and create the new ones with the right return type to do the same as LeadImage behavior.

**Comment by rodfersou** [comment]
Maybe we can add a monkey patch at collective.behavior.amp to fix collective.nitf package while our sites are not updated with the new implementations of Lead Image at collective.nitf.
