### ISSUE TITLE
Add support for amp-auto-ads

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.behavior.amp#51]
https://www.ampproject.org/docs/reference/components/ads/amp-auto-ads

**Comment by hvelarde** [comment]
difficult to implement as support is experimental and documentation far from complete.

**Comment by kakshay21** [comment]
Well, amp-ad is stable. Are we switching back to it? @hvelarde

**Comment by hvelarde** [comment]
we're making tests right know; I'll let you know.
